routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EbookController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PageController::class , 'welcome']);

Auth::routes();

Route::get('admin/home', [HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');
Route::get('admin/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard')->middleware('is_admin');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/profile/{id}' , [ProfileController::class , 'index']);

Route::resource('ebooks' , EbookController::class);
Route::get('/members' , [MemberController:: class , 'index']);
Route::post('/members' , [MemberController:: class , 'store'])->name('members.store');
Route::get('/members/create' , [MemberController:: class , 'create'])->name('members.create');
Route::delete('/members/{id}' , [MemberController:: class , 'destroy'])->name('members.destroy');
Route::get('/members/{id}' , [MemberController:: class , 'show'])->name('members.show');

Route::get('/ebook', [PageController::class , 'ebook']);
Route::get('/contact', [PageController::class , 'contact']);


// Route::get('/admin/profile/{id}' , [ProfileController::class , 'index']);

app/Models/Ebook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ebook extends Model
{
    use HasFactory;

    protected $table = 'ebooks';
    public $primaryKey = 'id';
    public $foreignKey = 'cat_id';
    public $timeStamps = true; 
    
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'author',
        'notes',
        'pic',
        'pdf',
        'cat_id',
    ];
    public function catagory()
    {
        return $this->hasOne(Catagory::class ,'cat_id');
    }
}

app/Http/Controllers/EbookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ebook;
use Illuminate\Http\Request;
class EbookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ebooks = Ebook::all();
        return view('ebooks.index', ['ebooks'=> $ebooks]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ebooks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request ,[
        'name' => 'required',
        'author' => 'required',
        'notes' => 'required|max:100',
        'pic' => 'required|max:2000|image|mimes:jpeg,png,jpg,gif,svg',
        'pdf' => 'required|max:15000|mimes:pdf',

        ],[
            'name' => 'Enter valid Ebook Name',
            'author' => 'Enter valid Author name',
            'notes' => ['Enter some notes','Max contains 100 characters'],
            'pic' => ['Must upload an image','Cover picture size no more than 2 MB','Only images can be uploaded'],
            'pdf' => ['Must upload an ebook pdf file ','Cover picture size no more than 15 MB','Only pdf files can be uploaded'],
        ]);
        $ebook = new Ebook;
        if($request->file('pic') && $request->file('pdf'))
        {
            $cover = $request->file('pic');
            $doc = $request->file('pdf');

            $pic = "covers/".$cover->getClientOriginalName();
            $coverName = $cover->getClientOriginalName();
            $pdf = "docs/".$doc->getClientOriginalName();
            $docName = $doc->getClientOriginalName();
            $cover->move('covers/',$coverName);
            $doc->move('docs/',$docName);
            $ebook->pic = $pic;
            $ebook->pdf = $pdf;
        }
        $ebook->name = $request->name;
        $ebook->author = $request->author;
        $ebook->notes = $request->notes;
        $ebook->save();
        // return $request->file('pdf')->getSize();
        return redirect(route('ebooks.index'));
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $ebook = Ebook::find($id);
        return view('ebooks.show' , ['ebook' => $ebook]);
    }

    /**
     * Show the form for editing the specified resource.
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Ebook::find($id)->delete();

        return back();
    }
}

resources/views/ebooks/create.blade.php
@extends('dashboard.master')
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Adding Ebook</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Ebooks</a></li>
                    <li class="breadcrumb-item active">Add Ebook</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container d-flex flex-column p-5 border border-rounded bg-white w-50 ml-4">
    <form id="add-ebook-form" action="{{route('ebooks.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" name="name" class="form-control" placeholder="Enter Ebook Name"
                    value="{{old('name')}}">
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Author:</label>
            <div class="col-sm-10">
                <input type="text" name="author" class="form-control" placeholder="Enter Author Name"
                    value="{{old('author')}}">
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Notes</label>
            <div class="col-sm-10">
                <textarea name="notes" class="form-control" cols="30" rows="10" placeholder="Enter Notes"></textarea>
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label">Cover Photo</label>
            <div class="col-sm-10">
                <input type="file" class="form-control" name="pic" style="border:none; color:green; font-size:1.1rem;"
                    accept="image/*">
            </div>
        </div>
        <div class="row mb-3">
            <label class="col-sm-2 col-form-label"> Ebook File</label>
            <div class="col-sm-10">
                <input type="file" class="form-control" name="pdf" style="border:none; color:green; font-size:1.1rem;"
                    accept="application/pdf">
            </div>
        </div>
        <button type="submit" class="btn btn-primary float-right" style="width:6rem; height:3rem;"> <i
                class="fas fa-plus"></i>
            Add</button>
    </form>
</div>
@endsection

resources/views/ebooks/index.blade.php
@extends('dashboard.master')
@section('content')
<style>
	.ebook {
		position: relative;
		display: inline-block;
		width: 21.35%;
		height: auto;
		margin: 1rem;
	}

	.ebook-img {
		display: block;
		width: 100%;
		height: 33vh;
	}

	.overlay {
		position: absolute;
		top: 0;
		bottom: 0;
		left: 0;
		right: 0;
		height: 100%;
		width: 100%;
		opacity: 0;
		transition: .5s ease;
		background-color: #2e2e2e;
	}

	.ebook:hover .overlay {
		opacity: 0.9;
	}

	.overlay-content {
		padding: 1rem;
		width: 100%;
		height: 100%;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		font-size: 1rem;
	}

	.action-btns {
		display: flex;
		font-size: 1.5rem;
		flex-direction: row;
		align-items: center;
		justify-content: center;
	}

	.ebooks-rack {
		display: inline-block;
		width: 100%;
	}
</style>
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Ebooks</h1>
			</div>
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="#">Home</a></li>
					<li class="breadcrumb-item active">Ebooks</li>
				</ol>
			</div>
		</div>
	</div>
</div>
<div class="container-fluid d-flex flex-column p-1 border border-rounded bg-white">
	<div class="add-ebook mt-3 mx-3">
		<a href="{{ route('ebooks.create')}}">
			<button>
				<i class="fas fa-plus"></i>
				Add Ebook
			</button>
		</a>
	</div>
	<div class="ebooks-rack">
		@foreach ($ebooks as $ebook)
		<div class="ebook">
			<img src="{{asset($ebook->pic)}}" alt="Avatar" class="ebook-img">
			<div class="overlay">
				<div class="overlay-content">
					<p class="text-white"><strong> Name:</strong> {{$ebook->name}}</p>
					<p class="text-white"><strong> Author:</strong> {{$ebook->author}}</p>
					<p class="text-white"><strong> Notes:</strong> <small>{{$ebook->notes}}</small></p>
					<div class="action-btns">
						<a class="px-2" href="{{route('ebooks.show' , $ebook->id) }}"><button><i
									class="fas fa-eye"></i></button></a>

						<form class="delete-ebook-form" action="{{ route('ebooks.destroy',$ebook->id) }}" method='POST'>
							@csrf
							@method('DELETE')
							<button type="submit"><i class="far fa-trash-alt"></i></button>
						</form>
					</div>
				</div>
			</div>

		</div>
		@endforeach
	</div>
</div>

@endsection

resources/views/ebooks/show.blade.php
@extends('dashboard.master')
@section('content')
<style>
    .ebook-container {
        width: 100%;
        height: 100%;
    }
</style>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Read Ebook</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Ebooks</a></li>
                    <li class="breadcrumb-item active">View Ebook</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="ebook-container d-flex flex-column p-4 border border-rounded bg-white">
    <div class="name">
        <p class="fs-4"><strong>Name: </strong>{{$ebook->name}}</p>
    </div>
    <div class="author">
        <p><strong>Author: </strong>{{$ebook->author}}</p>
    </div>
    <div class="notes">
        <p><strong>Notes: </strong>{{$ebook->notes}}</p>
    </div>
    <div class="pdf">
        <iframe src="{{asset($ebook->pdf)}}" id="Iframe" width="100%" height="100%"></iframe>
    </div>
</div>
<script>
    var frame = document.getElementById("Iframe");
          frame.onload = function()
          {
            frame.style.height = 
            frame.contentWindow.document.body.scrollHeight + '100vh';
            frame.style.width  = 
            frame.contentWindow.document.body.scrollWidth+'px';
                
          }
</script>
@endsection